FROM golang:1.22.3 AS builder


#ENV GOPROXY=https://goproxy.io,direct

WORKDIR /usr/src/app
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /usr/src/app/service ./movie/cmd/*.go


FROM scratch
COPY --from=builder /usr/src/app/service /service
COPY --from=builder /usr/src/app/metadata/configs/base.yaml /configs/base.yaml

EXPOSE 8083
ENTRYPOINT [ "/service" ]