FROM golang:1.22.3 as builder

WORKDIR /usr/src/app
COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /movie cmd/*.go


FROM scratch
COPY --from=builder /movie /movie

EXPOSE 8083
ENTRYPOINT [ "/movie" ]